name: Deploy

on:
  # On push
  push:
    branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout build
      uses: actions/checkout@v3
    
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
    - name: Composer Setup
      uses: php-actions/composer@v6
      with:
        dev: yes
        php_version: "7.4"
        version: latest
        command: install
      
    - name: Copy to build dir
      run: |
        mkdir build
        rsync -rvt --delete --include 'vendor' --exclude-from='.gitignore' --exclude '.git*' --exclude 'build' ./ build/
      
    - name: WordPress Plugin Deploy
      id: deploy
      uses: richard-muvirimi/deploy-wordpress-plugin@development
      with:
        svn-username: ${{ secrets.SVN_USERNAME }}
        svn-password: ${{ secrets.SVN_PASSWORD }}
        plugin-repository: woo-custom-gateway
        working-directory: build
